Lesson 3
====================================================================================================

## Reading in Data
```{r}
#setwd("/home/bruno/Documents/DataScienceForBusiness")
list.files()

pf <- read.csv("pseudo_facebook.tsv", sep = '\t')
#or read.delim('pseudo_facebook.tsv')
names(pf)
```

## Histogram of Users' birthdays
```{r}
install.packages('ggplot2')
library(ggplot2)

ggplot(aes(x = dob_day), data = pf) +
  geom_histogram(binwidth = 0.5) +
  scale_x_continuous(breaks = 1:31)
?scale_x_continuous
```

## Faceting
```{r}
ggplot(data = pf, aes(x = dob_day)) +
  geom_histogram(binwidth = 1) +
  scale_x_continuous(breaks = 1:31) +
  facet_wrap(~dob_month, ncol=3)
```

## Friend Count

```{r}
ggplot(aes(x = friend_count), data = pf) +
  geom_histogram(binwidth = 25) +
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0, 1000, 50))

```


## Friends count for man and woman
```{r}
ggplot(aes(x = friend_count), data = pf) +
  geom_histogram(binwidth = 25) +
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0, 1000, 50)) +
  facet_wrap(~gender, ncol=2)
```

## Friends count for man and woman excluding man and woman
```{r}
ggplot(aes(x = friend_count), data = subset(pf, !is.na(gender))) +
  geom_histogram(binwidth = 10) +
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0, 1000, 50)) +
  facet_wrap(~gender)
```

## Statistics by gender
```{r}
by(pf$friend_count, pf$gender, summary)
```


## Tenure
```{r}
ggplot(aes(x = tenure), data = pf) +
  geom_histogram(binwidth = 30, color = 'black', fill = '#099DD9')
```

## Tenure in years
```{r}
ggplot(aes(x = tenure/365), data = pf) +
  geom_histogram(binwidth = .25, color = 'black', fill = '#F79420')
```


## Labeling plots
```{r}
ggplot(aes(x = tenure / 365), data = pf) +
  geom_histogram(color = 'black', fill = '#F79420') +
  scale_x_continuous(breaks = seq(1, 7, 1), limits = c(0, 7)) +
  xlab('Number of years using Facebook') +
  ylab('Number of users in sample')
```


## User ages
```{r}
ggplot(aes(x = age), data = pf) +
  geom_histogram(binwidth = 1, color='black', fill = '#5760AB') +
  scale_x_continuous(breaks = seq(0, 113, 5))
```
```{r}
summary(pf$age)
```

## Transforming Data

```{r}
summary(pf$friend_count)
```
```{r}
summary(log10(pf$friend_count + 1)) # plus 1 for don't calculate log10(0) and get infinite values
```
```{r}
summary(sqrt(pf$friend_count)) # plus 1 for don't calculate log10(0) and get infinite values
```




```{r}
p1 <- ggplot(aes(x = friend_count), data = pf) +
  geom_histogram()
#p2 <- ggplot(aes(x = log10(friend_count)), data = pf) +
#  geom_histogram()
p2 <- p1 + scale_x_log10()
#  geom_histogram()
#p3 <- ggplot(aes(x = sqrt(friend_count)), data = pf) +
#  geom_histogram()
p3 <- p1 + scale_x_sqrt()

#install.packages("gridExtra")
library(gridExtra)
grid.arrange(p1, p2, p3, ncol = 1)
```

## Frequency Plygons
```{r}
ggplot(aes(x = friend_count, y = ..count../sum(..count..)),
       data = subset(pf, !is.na(gender))) +
  geom_freqpoly(aes(color = gender), binwidth=10) +
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0, 1000, 50)) +
  xlab('Friend Count') +
  ylab('Proportion of users with that friend count')
```

## Frequency Polygons Likes
```{r}
ggplot(aes(x = www_likes), data = subset(pf, !is.na(gender))) +
  geom_freqpoly(aes(color = gender)) +
  scale_x_log10()

```

```{r}
by(pf$www_likes, pf$gender, sum)
```


## Box Plots
```{r}
## Removing points, so alter IQR and median
ggplot(aes(x = gender, y = friend_count), data = subset(pf, !is.na(gender))) +
   scale_y_continuous(limits = c(0, 1000)) +
  geom_boxplot() 
  
```

```{r}
## Don't remove points, so alter coord scales
ggplot(aes(x = gender, y = friend_count), data = subset(pf, !is.na(gender))) +
   coord_cartesian(ylim= c(0, 250)) +
  geom_boxplot() 
  
```


```{r}
by(pf$friend_count, pf$gender, summary)
```



## Friendships Initiated

```{r}
ggplot(aes(x = gender, y = friendships_initiated), data = subset(pf, !is.na(gender))) +
   coord_cartesian(ylim= c(0, 200)) +
   geom_boxplot() 
```


```{r}
by(pf$friend_count, pf$gender, summary)
```


## Getting Logical
```{r}
summary(pf$mobile_likes)
```

```{r}
summary(pf$mobile_likes > 0)
```
```{r}
pf$mobile_check_in <- NA
pf$mobile_check_in <- ifelse(pf$mobile_likes > 0, 1, 0)
pf$mobile_check_in <- factor(pf$mobile_check_in)
summary(pf$mobile_check_in)
```

```{r}
#% percentage using mobile check-in
sum(pf$mobile_check_in == 1)/length(pf$mobile_check_in)
```














