---
title: "OneVariableExercises"
author: "Bruno Araujo"
date: "1 de março de 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(ggplot2)
data("diamonds")
summary(diamonds)
```
```{r}
dim(diamonds)

```

```{r}
str(diamonds)
```


```{r}
?diamonds
diamonds$color
```

# Create a histogram of the price of
# all the diamonds in the diamond data set.
```{r}
ggplot(aes(x = price), data = diamonds) +
  geom_histogram(binwidth = 500, color = 'black', fill ='#5760AB')
```

```{r}
summary(diamonds$price)
```


```{r}
less500 <- subset(diamonds, price < 500, select = (price))
less250 <- subset(diamonds, price < 250, select = (price))
more_eq_15000 <- subset(diamonds, price >= 15000, select = (price))

length(less500$price)
length(less250$price)
length(more_eq_15000$price)
```

```{r}
ggplot(aes(x = price), data = diamonds) +
  geom_histogram(binwidth = 10, color = 'black', fill ='#5760AB') +
  scale_x_continuous(breaks = seq(1000,2000,100), limits = c(1000,2000)) +
  xlab('Diamond\'s Price') +
  ylab('Number of Diamonds')
```
  
```{r}
 ggplot(aes(x = price), data = diamonds) +
  geom_histogram(binwidth = 200, color = 'black', fill ='#5760AB') +
  scale_x_continuous(breaks = seq(0,12500,2500),limits = c(0,12500)) +
  facet_wrap(~cut, ncol = 3, scales = "free_y")
```
  
```{r}
by(diamonds$price, diamonds$cut, summary)
```

```{r}
qplot(x = price, data = diamonds) + facet_wrap(~cut, scales ="free_y")  
```
  


```{r}
 ggplot(aes(x = carat), data = diamonds) +
  geom_histogram(binwidth = 0.1, color = 'black', fill ='#5760AB') +
  facet_wrap(~cut, ncol = 3, scales = "free_y") +
  scale_x_log10()
```



```{r}
ggplot(aes(x = color, y = price), data = diamonds) +
   scale_y_continuous(limits = c(0,6000)) +
  geom_boxplot() 
  
```
  
  
```{r}
by(diamonds$price, diamonds$color, summary)
```

```{r}
IQR(subset(diamonds, color == "J")$price)


```

```{r}
IQR(subset(diamonds, color == "D")$price)
```

  